<?php

/**
 * --------------------------------------------------------------------------
 * File path + filename: setup.php
 * --------------------------------------------------------------------------
 * Purpose:
 * - Bootstrap theme-level WordPress setup for the Sage theme.
 * - Load editor assets and generated theme.json integration.
 * - Register global theme features such as menus, supports, and sidebars.
 * - Enqueue shared admin/editor helper assets.
 * - Load the theme's support modules from the `app/Support` tree.
 *
 * Why this file exists:
 * - In this project, `setup.php` acts as the top-level boot file for the theme.
 * - It is the first place a future developer should inspect when asking:
 *   - "What features does the theme enable?"
 *   - "Which support modules are loaded globally?"
 *   - "Where are editor/admin helpers attached?"
 *
 * Important maintenance notes:
 * - This file intentionally mixes two kinds of bootstrapping:
 *   1) WordPress hook registrations for theme/editor/admin behavior
 *   2) `require_once` loaders for support modules contained in the theme
 * - The long-term ideal would be to split these concerns into smaller boot files,
 *   but this version keeps the existing code behavior intact and improves only
 *   readability, discoverability, and inline documentation.
 *
 * Scope:
 * - No runtime behavior is changed here.
 * - The execution order of the existing code is intentionally preserved.
 */

namespace App;

use Illuminate\Support\Facades\Vite;

/* =============================================================================
 * BLOCK EDITOR ASSET INJECTION
 * =============================================================================
 *
 * These hooks connect Sage/Vite-built editor assets to Gutenberg.
 *
 * Why this lives here:
 * - These are theme-wide editor concerns, not page-specific or module-specific.
 * - Keeping them near the top makes it obvious how editor styles/scripts enter
 *   WordPress.
 *
 * Sage/Vite context:
 * - The theme uses Vite-generated `editor.css`, `editor.js`, and the generated
 *   dependency manifest to support the block editor experience.
 * - The `Vite` facade is used to resolve built assets from PHP.
 * =============================================================================
 */

/**
 * Inject compiled editor styles into the block editor settings payload.
 *
 * Why this approach:
 * - This makes the compiled editor stylesheet available inside Gutenberg without
 *   manually hardcoding the built file path.
 * - It keeps the editor using the same build pipeline as the frontend theme.
 *
 * @param array $settings Existing block editor settings array.
 * @return array
 */
add_filter('block_editor_settings_all', function ($settings) {
    $style = Vite::asset('resources/css/editor.css');

    $settings['styles'][] = [
        'css' => "@import url('{$style}')",
    ];

    return $settings;
});

/**
 * Inject compiled editor scripts and any generated dependencies into Gutenberg.
 *
 * Why this exists:
 * - Some block editor scripts may rely on dependency handles generated by the
 *   Vite/Laravel build process.
 * - This hook ensures those dependencies are enqueued before the editor entry
 *   script is printed.
 *
 * Why `admin_head` is used here:
 * - The logic is scoped to block editor screens only by checking
 *   `get_current_screen()?->is_block_editor()`.
 *
 * @return void
 */
add_filter('admin_head', function () {
    if (! get_current_screen()?->is_block_editor()) {
        return;
    }

    $dependencies = json_decode(Vite::content('editor.deps.json'));

    foreach ($dependencies as $dependency) {
        if (! wp_script_is($dependency)) {
            wp_enqueue_script($dependency);
        }
    }

    echo Vite::withEntryPoints([
        'resources/js/editor.js',
    ])->toHtml();
});

/* =============================================================================
 * GENERATED theme.json HANDOFF
 * =============================================================================
 *
 * This project uses the build-generated `theme.json` rather than a manually
 * maintained root-level file.
 *
 * Why this matters:
 * - It keeps the editor design tokens aligned with the build output.
 * - It makes the generated file the effective source used by WordPress.
 * =============================================================================
 */

/**
 * Tell WordPress to use the generated `public/build/assets/theme.json`.
 *
 * Why this exists:
 * - The theme build process generates a `theme.json` file that reflects the
 *   design/token pipeline.
 * - This filter swaps WordPress's default theme file lookup so the generated
 *   file is used instead.
 *
 * @param string $path Resolved file path.
 * @param string $file Requested file name.
 * @return string
 */
add_filter('theme_file_path', function ($path, $file) {
    return $file === 'theme.json'
        ? public_path('build/assets/theme.json')
        : $path;
}, 10, 2);

/* =============================================================================
 * CORE THEME SETUP
 * =============================================================================
 *
 * This is the canonical WordPress theme setup section.
 *
 * Why `after_setup_theme` is important:
 * - WordPress expects core theme supports and menu registration to happen here.
 * - This hook runs early enough for features such as thumbnails and title-tag.
 * =============================================================================
 */

/**
 * Register the base theme setup.
 *
 * What belongs here:
 * - Theme supports
 * - Menu registration
 * - Broad theme feature toggles
 *
 * What does NOT belong here:
 * - Module loaders
 * - Admin-only CSS helpers
 * - Request-specific business logic
 *
 * @return void
 */
add_action('after_setup_theme', function () {
    /**
     * Disable block templates / full-site editing templates.
     *
     * Why:
     * - This theme is being used as a classic/Sage theme with Blade templates,
     *   not as an FSE-first theme.
     */
    remove_theme_support('block-templates');

    /**
     * Register navigation menu locations.
     *
     * These keys are the canonical handles used by the theme when requesting
     * menus in Blade/templates.
     */
    register_nav_menus([
        'primary_navigation'    => __('Primary Navigation', 'sage'),
        'legal_navigation'      => __('Legal Navigation', 'sage'),
    ]);

    /**
     * Disable WordPress core block patterns.
     *
     * Why:
     * - This keeps the editor more curated and avoids exposing default pattern
     *   choices that may not match the project design system.
     */
    remove_theme_support('core-block-patterns');

    /**
     * Allow WordPress/plugins to manage the document title tag.
     */
    add_theme_support('title-tag');

    /**
     * Enable featured image / post thumbnail support.
     */
    add_theme_support('post-thumbnails');

    /**
     * Enable responsive embedded content support.
     */
    add_theme_support('responsive-embeds');

    /**
     * Enable HTML5 markup support for common theme-generated elements.
     *
     * Why:
     * - Keeps theme output aligned with modern core markup expectations.
     */
    add_theme_support('html5', [
        'caption',
        'comment-form',
        'comment-list',
        'gallery',
        'search-form',
        'script',
        'style',
    ]);

    /**
     * Enable selective refresh support in the customizer.
     */
    add_theme_support('customize-selective-refresh-widgets');
}, 20);

/* =============================================================================
 * SIDEBAR / WIDGET AREAS
 * =============================================================================
 *
 * These are registered separately from the base theme setup because WordPress
 * expects sidebars to be registered on `widgets_init`.
 * =============================================================================
 */

/**
 * Register theme sidebars.
 *
 * Shared wrapper config is defined once and merged into each sidebar to keep
 * widget wrappers consistent.
 *
 * @return void
 */
add_action('widgets_init', function () {
    $config = [
        'before_widget' => '<section class="widget %1$s %2$s">',
        'after_widget' => '</section>',
        'before_title' => '<h3>',
        'after_title' => '</h3>',
    ];

    /**
     * Primary sidebar.
     *
     * General-purpose sidebar area.
     */
    register_sidebar([
        'name' => __('Primary', 'sage'),
        'id' => 'sidebar-primary',
    ] + $config);

    /**
     * Blog-only sidebar.
     *
     * Intended for blog index / archive / related editorial templates.
     */
    register_sidebar([
        'name' => __('Blog Sidebar', 'sage'),
        'id' => 'blog-sidebar',
    ] + $config);

    /**
     * Footer widget area.
     */
    register_sidebar([
        'name' => __('Footer', 'sage'),
        'id' => 'sidebar-footer',
    ] + $config);

    /**
     * Author widget area.
     */
    register_sidebar([
        'name' => __('Author Sidebar', 'sage'),
        'id' => 'author-archive-sidebar',
    ] + $config);    
});

/* =============================================================================
 * SHARED FONT ENQUEUES
 * =============================================================================
 *
 * These two hooks load the same Google Fonts family in two contexts:
 * - Frontend
 * - Block editor
 *
 * Why they remain separate:
 * - WordPress uses different enqueue hooks for the frontend and editor.
 * =============================================================================
 */

/**
 * Enqueue project fonts on the frontend.
 *
 * Priority is set to 100 so this loads after many default/frontend assets.
 */
add_action('wp_enqueue_scripts', function () {
  wp_enqueue_style(
    'scc-fonts',
    'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&family=Inter:wght@400;500;600&display=swap',
    [],
    null
  );
}, 100);

/**
 * Enqueue the same project fonts inside the block editor.
 *
 * Why:
 * - Improves WYSIWYG consistency between backend editing and frontend output.
 */
add_action('enqueue_block_editor_assets', function () {
  wp_enqueue_style(
    'scc-fonts-editor',
    'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&family=Inter:wght@400;500;600&display=swap',
    [],
    null
  );
});

/* =============================================================================
 * ADMIN-ONLY UI HELPERS
 * =============================================================================
 *
 * These are small ergonomic tweaks for wp-admin.
 * They are not business logic and are safe to think of as "polish helpers."
 * =============================================================================
 */

/**
 * Improve the ACF tab layout in admin by forcing a single-row tab strip with
 * horizontal scrolling when needed.
 *
 * Why this exists:
 * - Some larger field groups become hard to use when ACF wraps tabs awkwardly.
 * - This keeps tab navigation predictable on smaller admin widths.
 */
add_action('admin_enqueue_scripts', function () {
    $css = <<<CSS
    /* Keep ACF tabs in one row and allow horizontal scroll */
    .acf-fields .acf-tab-group{display:flex;flex-wrap:nowrap;gap:6px;overflow:auto}
    .acf-fields .acf-tab-group li{flex:0 0 auto}
    .acf-fields .acf-tab-group li a{white-space:nowrap}
    .acf-fields.-top > .acf-tab-wrap .acf-tab-group{margin-bottom:8px}
    CSS;

    /**
     * Prefer attaching the CSS to ACF's stylesheet handle if it is already
     * enqueued. If not, fall back to printing the CSS in `admin_head`.
     *
     * Why this fallback exists:
     * - It keeps the helper reliable even if ACF's enqueue timing differs
     *   slightly between screens.
     */
    if (wp_style_is('acf-input', 'enqueued')) {
        wp_add_inline_style('acf-input', $css);
    } else {
        add_action('admin_head', function () use ($css) {
            echo "<style>{$css}</style>";
        });
    }
});

/* =============================================================================
 * PARKED / LEGACY REFERENCE CODE
 * =============================================================================
 *
 * This section is intentionally commented out.
 *
 * Why it remains:
 * - It appears to be a historical sponsor CPT registration experiment/reference.
 * - Keeping it marked as legacy makes it clear this is not active runtime code.
 *
 * Recommendation for future cleanup:
 * - If nobody relies on this as reference material anymore, move it to project
 *   documentation or delete it entirely to reduce noise in the boot file.
 * =============================================================================
 */

// Sponsor Setup
// add_action( 'init', function() {

// 	register_extended_post_type( 'sponsor', array(

// 		# Add the post type to the site's main RSS feed:
// 		'show_in_feed' => true,

// 		# Use the block editor:
// 		'show_in_rest' => true,

// 		# Show all posts on the post type archive:
// 		'archive' => array(
// 			'nopaging' => true
// 		),

// 		# Add some custom columns to the admin screen:
// 		'admin_cols' => array(
// 			'featured_image' => array(
// 				'title'          => 'Logo',
// 				'featured_image' => 'thumbnail'
// 			),
//             'title',
// 			'status' => array(
// 				'taxonomy' => 'status'
//             ),
//             'class' => array(
// 				'taxonomy' => 'class'
// 			),
//             'published' => array(
// 				'title'       => 'Published',
// 				'meta_key'    => 'published_date',
// 				'date_format' => 'd/m/Y'
// 			),
// 		),

// 		# Add a dropdown filter to the admin screen:
// 		'admin_filters' => array(
// 			'status' => array(
// 				'taxonomy' => 'status'
//             ),
//             'class' => array(
// 				'taxonomy' => 'class'
// 			)
// 		)

// 	), array(

// 		# Override the base names used for labels:
// 		'singular' => 'Sponsor',
// 		'plural'   => 'Sponsors',
// 		'slug'     => 'sponsor'

// 	) );

// } );
// add_action('admin_init', function () {
//   error_log('Extended CPTs available: ' . (function_exists('extended_register_post_type') ? 'YES' : 'NO'));
// });

/* =============================================================================
 * SUPPORT MODULE LOADERS
 * =============================================================================
 *
 * From here down, `setup.php` acts as a module loader.
 *
 * Reading tip for future developers:
 * - If you are looking for "where does feature X come from?", scan these groups.
 * - The grouping below is organizational only; it does not change behavior.
 *
 * Maintenance rule of thumb:
 * - Keep low-level/global support files near the top.
 * - Keep domain-specific feature modules grouped by concern.
 * =============================================================================
 */

/* -----------------------------------------------------------------------------
 * Global media / transport / platform compatibility
 * -------------------------------------------------------------------------- */

require_once get_theme_file_path('app/Support/Media/ForceHttpsMediaUrls.php');

/* -----------------------------------------------------------------------------
 * Commerce / membership checkout glue
 * -------------------------------------------------------------------------- */

require_once get_theme_file_path('app/woocommerce/membership-checkout-fields.php');

// Legacy / replaced role file kept commented for reference.
// require_once get_theme_file_path('app/Support/Members/MemberRole.php');

require_once get_theme_file_path('app/Support/Members/MemberRoleSync.php');
require_once get_theme_file_path('app/Fields/EventSignupSettings.php');
/* -----------------------------------------------------------------------------
 * Operational roles + admin access (before CPTs so register_post_type_args runs first)
 * -------------------------------------------------------------------------- */

require_once get_theme_file_path('app/Support/Admin/UserRoles/bootstrap.php');

/* -----------------------------------------------------------------------------
 * Custom post types and their support files
 * -------------------------------------------------------------------------- */

require_once get_theme_file_path('app/Support/CPT/thank_you.php');
require_once get_theme_file_path('app/Support/CPT/sponsors.php');
require_once get_theme_file_path('app/Support/CPT/minutes.php');
require_once get_theme_file_path('app/Support/CPT/leadership.php');
require_once get_theme_file_path('app/Support/CPT/LeadershipMetaBoxes.php');
require_once get_theme_file_path('app/Support/CPT/LeadershipPositionExclusivity.php');
require_once get_theme_file_path('app/Support/CPT/Faq.php');
require_once get_theme_file_path('app/Support/CPT/TestimonialPostType.php');

/* -----------------------------------------------------------------------------
 * Admin dashboard reports and admin-user tooling
 * -------------------------------------------------------------------------- */

// Admin Reports (after UserRoles bootstrap; widgets rely on sccc_* capabilities)
require_once get_theme_file_path('app/Support/Admin/Dashboard/Reports/BirthdaysReport.php');
require_once get_theme_file_path('app/Support/Admin/Dashboard/Reports/AnniversariesReport.php');
require_once get_theme_file_path('app/Support/Admin/Dashboard/Reports/CarsReport.php');
require_once get_theme_file_path('app/Support/Admin/Dashboard/Reports/VeteransReport.php');
require_once get_theme_file_path('app/Support/Admin/Dashboard/Reports/CarParkReport.php');
require_once get_theme_file_path('app/Support/Admin/Dashboard/Reports/MembershipTrendsReport.php');
// ManualRoleAssignment superseded by App\Support\Admin\UserRoles\SecondaryRoleAssignment (see bootstrap above).
// require_once get_theme_file_path('app/Support/Admin/Users/ManualRoleAssignment.php');
require_once get_theme_file_path('app/Support/Admin/Users/MemberColumns.php');
require_once get_theme_file_path('app/Support/Admin/Users/BulkPasswordResetMail.php');

/* -----------------------------------------------------------------------------
 * Featured vehicle system
 * -------------------------------------------------------------------------- */

require_once get_theme_file_path('app/Support/FeaturedVehicles/RegisterFeaturedVehiclePostType.php');
require_once get_theme_file_path('app/Support/FeaturedVehicles/FeaturedVehicleResolver.php');
require_once get_theme_file_path('app/Support/FeaturedVehicles/FeaturedVehicleArchiveRepository.php');

/* -----------------------------------------------------------------------------
 * Membership / WooCommerce / PMPro integrations
 * -------------------------------------------------------------------------- */

// Integrations
require_once get_theme_file_path('app/Support/Integrations/PmproWooBillingSync.php');
require_once get_theme_file_path('app/Support/Integrations/WooMyAccountPmproMembershipEndpoint.php');
require_once get_theme_file_path('app/Support/Integrations/PmproAccountProfileLinksToWoo.php');
require_once get_theme_file_path('app/Support/Integrations/PmproRenewLinkWindow.php');
require_once get_theme_file_path('app/Support/Integrations/ScccMemberLifecycleAdmin.php');

/* -----------------------------------------------------------------------------
 * Woo account / event booking presentation helpers
 * -------------------------------------------------------------------------- */

require_once get_theme_file_path('app/Support/Woo/AccountEditExtras.php');
require_once get_theme_file_path('app/Support/Woo/EventBookingsBladeOverride.php');

/* -----------------------------------------------------------------------------
 * Member profile / perks / member-related support
 * -------------------------------------------------------------------------- */

require_once get_theme_file_path('app/Support/Members/VeteranStatusToggle.php');
require_once get_theme_file_path('app/Support/Members/LocalAvatar.php');
require_once get_theme_file_path('app/Support/Members/MemberDirectory.php');

// Parked taxonomy file kept commented for reference.
// require_once get_theme_file_path('app/Support/Taxonomies/BusinessDirectoryTaxonomies.php');

require_once get_theme_file_path('app/Support/Memberships/FoundingCap.php');
require_once get_theme_file_path('app/Support/PMPro/EventSignupFlow.php');
require_once get_theme_file_path('app/Support/Memberships/AbandonedSubscriberCleanup.php');
require_once get_theme_file_path('app/Support/Members/Garage.php');
require_once get_theme_file_path('app/Support/Members/MemberBio.php');

/* -----------------------------------------------------------------------------
 * Admin dashboard boot + auth helpers
 * -------------------------------------------------------------------------- */

require_once get_theme_file_path('app/Support/Admin/Dashboard/bootstrap.php');
require_once get_theme_file_path('app/Support/Auth/PrettyLogout.php');

/* -----------------------------------------------------------------------------
 * Admin configuration / dev safety / referral tooling
 * -------------------------------------------------------------------------- */

require_once get_theme_file_path('app/Support/Admin/config.php');
require_once get_theme_file_path('app/Support/Admin/WordPressBranding.php');
require_once get_theme_file_path('app/Support/Admin/Users/ReferralSourceField.php');
require_once get_theme_file_path('app/Support/Admin/UserRoles/AdminDashboardBackground.php');
require_once get_theme_file_path('app/Support/Dev/LocalSslStreamBypass.php');

require_once get_theme_file_path('app/Support/Marketing/ReferralSourceTracker.php');
require_once get_theme_file_path('app/Support/Marketing/GravityFormsCookiePopulation.php');

/* -----------------------------------------------------------------------------
 * Editorial / blog content systems
 * -------------------------------------------------------------------------- */

require_once get_theme_file_path('app/Support/Blog/ContentType.php');

/* -----------------------------------------------------------------------------
 * Frontend access and navigation control
 * -------------------------------------------------------------------------- */

require_once get_theme_file_path('app/Support/Access/ProtectedFrontendPages.php');
require_once get_theme_file_path('app/Support/Navigation/MenuItemRoleVisibility.php');

/* -----------------------------------------------------------------------------
 * Form integrations
 * -------------------------------------------------------------------------- */

require_once get_theme_file_path('app/Support/GravityForms/GravityFormsKLoggerBootstrap.php');
require_once get_theme_file_path('app/Support/GravityForms/SponsorApcSync.php');


require_once get_theme_file_path('app/Support/Woo/ShopNavigation.php');
require_once get_theme_file_path('app/Support/Woo/ProductMarkup.php');
require_once get_theme_file_path('app/Support/Woo/ShopVariationAttributeFilters.php');
require_once get_theme_file_path('app/Support/Woo/ProductAccess.php');
require_once get_theme_file_path('app/Support/Woo/EventProductAccess.php');
require_once get_theme_file_path('app/Support/Woo/EventFrontendCleanup.php');

/* -----------------------------------------------------------------------------
 * Security
 * -------------------------------------------------------------------------- */
require_once get_theme_file_path('app/Support/Security/StrongPasswords.php');

// require_once get_theme_file_path('app/Support/Security/PmproCheckoutNoAutoLogin.php');

/* =============================================================================
 * ICON FONT ENQUEUES
 * =============================================================================
 *
 * Material Symbols are used in both frontend and editor contexts, so they are
 * enqueued separately on the matching WordPress hooks.
 * =============================================================================
 */

/**
 * Enqueue Material Symbols on the frontend.
 */
add_action('wp_enqueue_scripts', function () {
    wp_enqueue_style(
        'sccc-material-symbols',
        'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200',
        [],
        null
    );
}, 20);

/**
 * Enqueue Material Symbols inside the editor.
 */
add_action('enqueue_block_editor_assets', function () {
    wp_enqueue_style(
        'sccc-material-symbols',
        'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200',
        [],
        null
    );
}, 20);

/* =============================================================================
 * DEBUG / ONE-OFF ADMIN UTILITIES
 * =============================================================================
 *
 * This section contains intentionally disabled debug/reset utilities.
 *
 * Why it stays commented:
 * - These helpers can be useful during development or admin repair tasks.
 * - They should remain clearly marked as non-production runtime code.
 * =============================================================================
 */

/* TEST */
// add_action('admin_init', function () {
//     if (!current_user_can('manage_options')) {
//         return;
//     }

//     if (!isset($_GET['sccc_reset_feature_vehicle'])) {
//         return;
//     }

//     $monthKey = current_time('Y-m');

//     $post = \App\Support\FeaturedVehicles\FeaturedVehicleResolver::findArchiveByMonth($monthKey);

//     if ($post) {
//         wp_delete_post((int) $post->ID, true);
//     }

//     \App\Support\FeaturedVehicles\FeaturedVehicleArchiveRepository::clearCacheForMonth($monthKey);

//     wp_die('Current month featured vehicle archive + cache cleared for ' . esc_html($monthKey) . '.');
// });

/* =============================================================================
 * PROJECT NOTE: CONTENT TYPE TAXONOMY
 * =============================================================================
 *
 * This trailing note documents the design intent for the Content Type taxonomy.
 * It is not executable code, but it is useful project knowledge.
 *
 * Recommendation:
 * - Keeping this note is reasonable because it explains editorial architecture.
 * - If you ever create dedicated internal docs, this is the kind of note that
 *   could move there instead of living in the boot file.
 * =============================================================================
 */

/*
 * Register the Content Type taxonomy.
 *
 * Why registered in code, terms managed in admin:
 * - The taxonomy structure (slug, rewrite rules, meta box behaviour) is
 *   architectural and belongs in version control.
 * - The actual terms (Event Recaps, Garage Talk…) are editorial content
 *   and belong in the database, managed via Posts → Content Types in
 *   wp-admin. This keeps code deploys and content management separate.
 *
 * To add/edit/delete terms:
 *   wp-admin → Posts → Content Types
 *
 * Why non-hierarchical + radio meta box:
 * - Content types are a flat, curated set — not a parent/child tree.
 * - Radio enforces one type per post (a post is a Spotlight OR Garage
 *   Talk, not both).
 *
 * Why mandatory (see validation hooks below):
 * - A post without a content type would not appear in any pill-filtered
 *   view and cannot be categorised correctly in the frontend.
 * - Validation is enforced at the REST API layer (Gutenberg) and at the
 *   wp_insert_post_data layer (classic editor) so neither editor can
 *   publish without selecting a type.
 */
