<?php
/**
 * File: app/Support/Admin/Dashboard/Reports/AnniversariesReport.php
 *
 * SCCC Admin Reports (HTML Print-to-PDF) — Membership Anniversaries
 * ============================================================================
 * PURPOSE
 * - Dashboard widget that lists SCCC members whose membership anniversary falls
 *   within the CURRENT month.
 * - “Print list” opens a clean HTML print view so staff can Save as PDF.
 *
 * WHY HTML PRINT (NOT PDF LIBRARY)
 * - Zero server dependencies
 * - Browser rendering is consistent and reliable for internal meeting sheets
 *
 * MEMBER SCOPE (CONFIRMED)
 * - Only users with WP role: `sccc_member`
 *
 * ADDITIONAL SCOPE (YOUR NEW RULE)
 * - This is a “community/engagement” report.
 * - Include: Active + Grace (0–29 days lapsed)
 * - Exclude: Past Due (30–59) + Abandoned (60+)
 * - Exclude: Paused
 *
 * FIELD SOURCE
 * - User meta key: `membership_issued_at`
 *
 * NOTES ABOUT DATE STORAGE
 * - This meta may appear in common formats (Ymd, Y-m-d, Y-m-d H:i:s).
 * - We query users with a non-empty value and filter by month in PHP.
 *
 * OUTPUT
 * - “Anniversary” column formatted like: “Mon 16th”
 * - “Years” column showing how many years since issued (as of the report year)
 * - Excludes 0-year anniversaries (members who joined this year)
 * - “Generated by” on print view
 *
 * IMPORTANT (Theme-scoped)
 * - This file must be INCLUDED by your theme bootstrap or it will never run.
 */

if (!defined('ABSPATH')) {
  exit;
}

/**
 * ---------------------------------------------------------------------------
 * Shared configuration (guarded to prevent constant redefinition warnings)
 * ---------------------------------------------------------------------------
 *
 * These constants are shared across multiple report files.
 * BirthdaysReport.php already defines them, so we only define them here if they
 * are not defined yet.
 */
if (!defined('SCCC_REPORTS_MEMBER_ROLE')) {
  define('SCCC_REPORTS_MEMBER_ROLE', 'sccc_member');
}

/**
 * ---------------------------------------------------------------------------
 * Report-specific configuration
 * ---------------------------------------------------------------------------
 */
const SCCC_MEMBERSHIP_ISSUED_META_KEY = 'membership_issued_at';

/**
 * ---------------------------------------------------------------------------
 * Helper: ordinal day suffix
 * ---------------------------------------------------------------------------
 *
 * BirthdaysReport.php defines sccc_ordinal(). If both files are loaded,
 * we must not redeclare it.
 */
if (!function_exists('sccc_ordinal')) {
  function sccc_ordinal(int $n): string
  {
    $n = abs($n);
    $mod100 = $n % 100;

    if ($mod100 >= 11 && $mod100 <= 13) {
      return $n . 'th';
    }

    switch ($n % 10) {
      case 1: return $n . 'st';
      case 2: return $n . 'nd';
      case 3: return $n . 'rd';
      default: return $n . 'th';
    }
  }
}

/**
 * ---------------------------------------------------------------------------
 * Helper: parse membership_issued_at safely
 * ---------------------------------------------------------------------------
 *
 * We accept the most common formats we might encounter:
 * - Ymd               (e.g. 20240116)
 * - Y-m-d             (e.g. 2024-01-16)
 * - Y-m-d H:i:s       (e.g. 2024-01-16 13:45:00)
 *
 * Returns DateTime|false
 */
function sccc_reports_parse_issued_date(string $raw)
{
  $raw = trim($raw);
  if ($raw === '') {
    return false;
  }

  if (preg_match('/^\d{8}$/', $raw)) {
    return DateTime::createFromFormat('Ymd', $raw) ?: false;
  }

  if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $raw)) {
    return DateTime::createFromFormat('Y-m-d', $raw) ?: false;
  }

  if (preg_match('/^\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}$/', $raw)) {
    return DateTime::createFromFormat('Y-m-d H:i:s', $raw) ?: false;
  }

  // Last resort: try PHP's date parser
  try {
    return new DateTime($raw);
  } catch (Exception $e) {
    return false;
  }
}

/**
 * ---------------------------------------------------------------------------
 * MEMBERSHIP STATUS FILTER (Active + Grace only)
 * ---------------------------------------------------------------------------
 *
 * This report is used for real-world outreach/community planning.
 * So we intentionally exclude members who are “seriously lapsed”.
 *
 * Definitions used here:
 * - Active: PMPro status='active' AND (enddate is empty OR enddate in future)
 * - Grace: membership ended, but within 0–29 days
 * - Past Due: 30–59 days (excluded)
 * - Abandoned: 60+ days (excluded)
 * - Paused: manual override (excluded)
 *
 * Notes:
 * - We DO NOT rely on the Users-table badge meta here because that meta is only
 *   guaranteed to be written when the Users screen is viewed.
 * - Instead, we compute directly from PMPro’s memberships_users table so this
 *   report is accurate on its own.
 */
if (!function_exists('sccc_reports_anniv_is_active_or_grace')) {
  function sccc_reports_anniv_is_active_or_grace(int $user_id): bool
  {
    // If they are paused (manual admin override), exclude from engagement reports.
    if ((int) get_user_meta($user_id, 'sccc_membership_paused', true) === 1) {
      return false;
    }

    // If PMPro table is missing, we can’t reliably decide. Safer to exclude.
    if (!sccc_reports_anniv_pmpro_table_exists()) {
      return false;
    }

    $row = sccc_reports_anniv_get_latest_pmpro_membership_row($user_id);
    if (!$row || !is_array($row)) {
      return false;
    }

    $now = current_time('timestamp');
    $status = isset($row['status']) ? (string) $row['status'] : '';
    $end_ts = sccc_reports_anniv_parse_enddate_to_ts($row['enddate'] ?? null);

    // Active if PMPro says active AND enddate is empty OR in the future.
    $has_end = ($end_ts !== null);
    $active_by_enddate = (!$has_end) || ($end_ts > $now);

    if ($status === 'active' && $active_by_enddate) {
      return true;
    }

    // Grace if membership ended within the last 0–29 days.
    if ($has_end && $end_ts <= $now) {
      $days = (int) floor(max(0, $now - $end_ts) / DAY_IN_SECONDS);
      return ($days >= 0 && $days < 30);
    }

    // Unknown/odd states are excluded (safer for outreach lists).
    return false;
  }
}

if (!function_exists('sccc_reports_anniv_pmpro_table_exists')) {
  function sccc_reports_anniv_pmpro_table_exists(): bool
  {
    global $wpdb;

    $table = sccc_reports_anniv_pmpro_memberships_users_table();
    if (!$table) {
      return false;
    }

    $like = $wpdb->esc_like($table);
    $found = $wpdb->get_var($wpdb->prepare("SHOW TABLES LIKE %s", $like)); // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared

    return !empty($found);
  }
}

if (!function_exists('sccc_reports_anniv_pmpro_memberships_users_table')) {
  function sccc_reports_anniv_pmpro_memberships_users_table(): string
  {
    global $wpdb;

    // If PMPro registered a property, prefer it.
    if (isset($wpdb->pmpro_memberships_users) && !empty($wpdb->pmpro_memberships_users)) {
      return (string) $wpdb->pmpro_memberships_users;
    }

    return (string) ($wpdb->prefix . 'pmpro_memberships_users');
  }
}

if (!function_exists('sccc_reports_anniv_get_latest_pmpro_membership_row')) {
  function sccc_reports_anniv_get_latest_pmpro_membership_row(int $user_id): ?array
  {
    global $wpdb;

    $table = sccc_reports_anniv_pmpro_memberships_users_table();
    if (!$table) {
      return null;
    }

    // “Latest” row by modified timestamp (then id) best reflects current state.
    $sql = "
      SELECT id, status, startdate, enddate, modified, membership_id
      FROM {$table}
      WHERE user_id = %d
      ORDER BY modified DESC, id DESC
      LIMIT 1
    ";

    $row = $wpdb->get_row($wpdb->prepare($sql, $user_id), ARRAY_A); // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared

    return is_array($row) ? $row : null;
  }
}

if (!function_exists('sccc_reports_anniv_parse_enddate_to_ts')) {
  function sccc_reports_anniv_parse_enddate_to_ts($enddate): ?int
  {
    if ($enddate === null) {
      return null;
    }

    $enddate = is_string($enddate) ? trim($enddate) : '';
    if ($enddate === '' || $enddate === '0000-00-00 00:00:00') {
      return null;
    }

    $ts = strtotime($enddate);
    return $ts ? (int) $ts : null;
  }
}

/**
 * ---------------------------------------------------------------------------
 * Boot: Dashboard widget registration
 * ---------------------------------------------------------------------------
 */
add_action('wp_dashboard_setup', function () {
  if (!current_user_can(\App\Support\Admin\UserRoles\OperationalRoles::CAP_USE_DASHBOARD_WIDGETS)) {
    return;
  }

  wp_add_dashboard_widget(
    'sccc_anniversaries_current_month',
    'SCCC Membership Anniversaries (Current Month)',
    'sccc_anniversaries_widget_render'
  );
});

/**
 * Render the Anniversaries dashboard widget
 * - Shows a compact table preview (first 10 rows)
 * - Provides a "Print list" button that opens a standalone print page
 */
function sccc_anniversaries_widget_render(): void
{
  if (!current_user_can(\App\Support\Admin\UserRoles\OperationalRoles::CAP_USE_DASHBOARD_WIDGETS)) {
    echo '<p>You do not have permission to view this report.</p>';
    return;
  }

  $monthNum  = (int) wp_date('n');
  $monthName = wp_date('F');

  $members = sccc_get_members_with_anniversary_in_month($monthNum);

  $printUrl = add_query_arg(
    [
      'action'    => 'sccc_print_anniversaries',
      'month'     => $monthNum,
      'autoprint' => 1,
    ],
    admin_url('admin-post.php')
  );

  $printUrl = wp_nonce_url($printUrl, 'sccc_print_anniversaries');

  echo '<p style="margin:0 0 .75rem;">';
  echo 'Showing members with anniversaries in <strong>' . esc_html($monthName) . '</strong>.';
  echo '</p>';

  echo '<p style="margin:0 0 1rem;">';
  echo '<a class="button button-primary" href="' . esc_url($printUrl) . '">Print list</a>';
  echo '</p>';

  if (empty($members)) {
    echo '<p style="margin:0;">No anniversaries found for this month.</p>';
    return;
  }

  $preview = array_slice($members, 0, 10);

  echo '<div style="max-height: 260px; overflow:auto; border:1px solid #dcdcde; border-radius:6px;">';
  echo '<table class="widefat striped" style="margin:0;">';
  echo '<thead><tr>';
  echo '<th style="width:130px;">Anniversary</th>';
  echo '<th style="width:80px;">Years</th>';
  echo '<th>Name</th>';
  echo '<th>Email</th>';
  echo '</tr></thead><tbody>';

  foreach ($preview as $row) {
    echo '<tr>';
    echo '<td>' . esc_html($row['anniversary_label']) . '</td>';
    echo '<td>' . esc_html((string) $row['years']) . '</td>';
    echo '<td>' . esc_html($row['name']) . '</td>';
    echo '<td>' . esc_html($row['email']) . '</td>';
    echo '</tr>';
  }

  echo '</tbody></table></div>';

  $total = count($members);
  if ($total > count($preview)) {
    echo '<p style="margin:.75rem 0 0; color:#646970;">';
    echo esc_html(sprintf('Showing %d of %d. Use “Print list” for the full sheet.', count($preview), $total));
    echo '</p>';
  }
}

/**
 * ---------------------------------------------------------------------------
 * Print endpoint (standalone HTML)
 * ---------------------------------------------------------------------------
 */
add_action('admin_post_sccc_print_anniversaries', function () {
  if (!current_user_can(\App\Support\Admin\UserRoles\OperationalRoles::CAP_USE_DASHBOARD_WIDGETS)) {
    wp_die('You do not have permission to print this report.');
  }

  check_admin_referer('sccc_print_anniversaries');

  $monthNum = isset($_GET['month']) ? (int) $_GET['month'] : (int) wp_date('n');
  if ($monthNum < 1 || $monthNum > 12) {
    $monthNum = (int) wp_date('n');
  }

  $autoPrint = !empty($_GET['autoprint']);

  $members   = sccc_get_members_with_anniversary_in_month($monthNum);
  $monthName = wp_date('F', strtotime(sprintf('2026-%02d-01', $monthNum)));
  $generated = wp_date('F j, Y g:i A');

  $currentUser = wp_get_current_user();
  $generatedBy = ($currentUser && $currentUser->exists())
    ? $currentUser->display_name
    : 'Unknown';

  header('Content-Type: text/html; charset=' . get_option('blog_charset'));

  ?>
  <!doctype html>
  <html lang="en">
    <head>
      <meta charset="<?php echo esc_attr(get_option('blog_charset')); ?>">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title><?php echo esc_html("SCCC Anniversaries — {$monthName}"); ?></title>
      <style>
        :root { --text:#111827; --muted:#6b7280; --border:#e5e7eb; }

        html, body { margin:0; padding:0; }
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
          color: var(--text);
          background: #fff;
          padding: 28px;
        }

        .topbar{
          display:flex; align-items:flex-start; justify-content:space-between; gap:16px;
          border-bottom: 2px solid var(--border);
          padding-bottom: 14px;
          margin-bottom: 16px;
        }

        h1 { font-size: 20px; line-height: 1.25; margin: 0 0 4px; }
        .meta { margin:0; color: var(--muted); font-size:12px; line-height:1.4; }
        .actions { display:flex; gap:10px; }

        .btn{
          appearance:none;
          border:1px solid #111827;
          background:#111827;
          color:#fff;
          padding:8px 12px;
          border-radius:6px;
          font-size:13px;
          cursor:pointer;
          text-decoration:none;
          display:inline-flex;
          align-items:center;
          justify-content:center;
        }
        .btn.secondary { background:#fff; color:#111827; }

        table { width:100%; border-collapse: collapse; font-size: 13px; }
        thead th { text-align:left; border-bottom:2px solid var(--border); padding:10px 8px; font-weight:700; }
        tbody td { border-bottom:1px solid var(--border); padding:9px 8px; vertical-align:top; }

        .col-ann { width: 130px; }
        .col-years { width: 80px; }
        .col-email { width: 34%; }

        .empty { padding: 12px 0; color: var(--muted); }

        @media print {
          body { padding: 0; }
          .actions { display:none !important; }
          .topbar { border-bottom: 1px solid #000; }
          a[href]::after { content: ""; }
        }
      </style>
    </head>
    <body>
      <div class="topbar">
        <div>
          <h1><?php echo esc_html("SCCC Anniversaries — {$monthName}"); ?></h1>
          <p class="meta">
            Generated: <?php echo esc_html($generated); ?><br>
            Generated by: <?php echo esc_html($generatedBy); ?>
          </p>
        </div>

        <div class="actions">
          <button class="btn" onclick="window.print()">Print / Save as PDF</button>
          <a class="btn secondary" href="<?php echo esc_url(admin_url()); ?>">Back to Dashboard</a>
        </div>
      </div>

      <?php if (empty($members)) : ?>
        <p class="empty">No anniversaries found for this month.</p>
      <?php else : ?>
        <table>
          <thead>
            <tr>
              <th class="col-ann">Anniversary</th>
              <th class="col-years">Years</th>
              <th>Name</th>
              <th class="col-email">Email</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($members as $row) : ?>
              <tr>
                <td class="col-ann"><?php echo esc_html($row['anniversary_label']); ?></td>
                <td class="col-years"><?php echo esc_html((string) $row['years']); ?></td>
                <td><?php echo esc_html($row['name']); ?></td>
                <td class="col-email"><?php echo esc_html($row['email']); ?></td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      <?php endif; ?>

      <?php if ($autoPrint) : ?>
        <script>
          window.addEventListener('load', () => setTimeout(() => window.print(), 250));
        </script>
      <?php endif; ?>
    </body>
  </html>
  <?php

  exit;
});

/**
 * ---------------------------------------------------------------------------
 * Data helper: members with anniversaries in a given month
 * ---------------------------------------------------------------------------
 *
 * Anniversary definition:
 * - Month of `membership_issued_at` matches the report month
 *
 * Years:
 * - reportYear - issuedYear
 *
 * EXCLUSION (requested):
 * - We skip 0-year anniversaries (issuedYear === reportYear)
 *
 * ADDITIONAL EXCLUSION (your new rule):
 * - Only include members who are Active or in Grace (0–29 days lapsed)
 * - Exclude Past Due, Abandoned, and Paused
 */
function sccc_get_members_with_anniversary_in_month(int $monthNum): array
{
  $monthNum   = max(1, min(12, $monthNum));
  $reportYear = (int) wp_date('Y');

  $query = new WP_User_Query([
    'role'       => SCCC_REPORTS_MEMBER_ROLE,
    'number'     => 9999,
    'orderby'    => 'display_name',
    'order'      => 'ASC',
    'meta_query' => [
      [
        'key'     => SCCC_MEMBERSHIP_ISSUED_META_KEY,
        'compare' => 'EXISTS',
      ],
      [
        'key'     => SCCC_MEMBERSHIP_ISSUED_META_KEY,
        'value'   => '',
        'compare' => '!=',
      ],
    ],
  ]);

  $users = $query->get_results();
  if (empty($users)) {
    return [];
  }

  $rows = [];

  foreach ($users as $user) {
    /**
     * STATUS GATE (Active + Grace only)
     * -----------------------------------------------------------------------
     * Keeps the report focused on members who are realistically still part of
     * the club’s active community right now.
     */
    if (!sccc_reports_anniv_is_active_or_grace((int) $user->ID)) {
      continue;
    }

    $raw = (string) get_user_meta($user->ID, SCCC_MEMBERSHIP_ISSUED_META_KEY, true);
    if ($raw === '') {
      continue;
    }

    $issued = sccc_reports_parse_issued_date($raw);
    if (!$issued) {
      continue;
    }

    $issuedYear  = (int) $issued->format('Y');
    $issuedMonth = (int) $issued->format('n');
    $issuedDay   = (int) $issued->format('j');

    if ($issuedMonth !== $monthNum) {
      continue;
    }

    $years = ($issuedYear > 0) ? ($reportYear - $issuedYear) : '';

    // Skip 0-year anniversaries (members who joined this year)
    if ($years === '' || $years < 1) {
      continue;
    }

    $annThisYear = DateTime::createFromFormat('Y-n-j', $reportYear . '-' . $issuedMonth . '-' . $issuedDay);
    if (!$annThisYear) {
      continue;
    }

    $weekday = $annThisYear->format('D');
    $ordinal = sccc_ordinal((int) $annThisYear->format('j'));
    $label   = $weekday . ' ' . $ordinal;

    $rows[] = [
      'id'                => (int) $user->ID,
      'name'              => (string) $user->display_name,
      'email'             => (string) $user->user_email,
      'issued_raw'        => $raw,
      'day'               => $issuedDay,
      'anniversary_label' => $label,
      'years'             => $years,
    ];
  }

  usort($rows, function ($a, $b) {
    if ($a['day'] === $b['day']) {
      return strcasecmp($a['name'], $b['name']);
    }
    return $a['day'] <=> $b['day'];
  });

  return $rows;
}
